-- local handle = io.popen("cat ~/.color")
-- if handle ~= nil then
--   local back = handle:read("*a")
--   handle:close()
--
--   if string.find(back, "dark") then
--     vim.cmd("colorscheme kanagawa-wave")
--     vim.cmd [[set cursorline]]
--   else
--     vim.cmd("colorscheme kanagawa-lotus")
--     vim.cmd [[set cursorline]]
--   end
--
--   return {
--     X = back
--   }
-- end
vim.cmd("colorscheme kanagawa")
