source-file ~/.config/omf/tmux/global.tmux.conf
source-file ~/.config/omf/tmux/light-2.tmux.conf

if-shell '[ $(cat ~/.color) = light ]' {
  # light
  set -g status-style 'bg=colour7 fg=colour137 dim'
  # - Right Side
  set -g status-right '#[fg=colour0, bg=colour12 bold] %d/%m #[fg=colour0, bg=colour11 bold] %H:%M:%S '
  # - Left Side
  ## Current selected
  setw -g window-status-current-style 'fg=colour0 bg=colour125 bold'
  setw -g window-status-current-format ' #I#[fg=colour0]:#[fg=colour0]#W#[fg=colour0]#F '
  ## Not selected
  setw -g window-status-style 'fg=colour0 bg=colour7'
  setw -g window-status-format ' #I#[fg=colour0]:#[fg=colour0]#W#[fg=colour0]#F '
  setw -g window-status-bell-style 'fg=colour0 bg=colour1 bold'
  # - cmd line
  set -g message-style 'fg=colour0 bg=colour7 bold'
}


if-shell '[ $(cat ~/.color) = dark ]' {
  set -g status-style 'bg=colour16 fg=colour137 dim'
  set -g status-right '#[fg=colour17 bold,bg=colour2] %d/%m #[fg=colour214, bg=colour234] %H:%M:%S '
  # - Left Side
  ## Current selected
  setw -g window-status-current-style 'fg=colour13 bg=colour57 bold'
  setw -g window-status-current-format ' #I#[fg=colour7]:#[fg=colour7]#W#[fg=colour7]#F '
  ## Not selected
  setw -g window-status-style 'fg=colour204 bg=colour234'
  setw -g window-status-format ' #I#[fg=colour247]:#[fg=colour250]#W#[fg=colour244]#F '
  setw -g window-status-bell-style 'fg=colour0 bg=colour1 bold'
  # - cmd line
  set -g message-style 'fg=colour7 bg=colour0 bold'
}

# Copy
set-option -s set-clipboard off
bind P paste-buffer
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X rectangle-toggle
unbind -T copy-mode-vi Enter
bind-key -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel 'xclip -selection clipboard'
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel 'xclip -selection clipboard'


