-- Basic
vim.keymap.set({ "n", "v" }, "<C-h>", "0")
vim.keymap.set({ "n", "v" }, "<C-l>", "$")
vim.keymap.set("v", "R", "p")
vim.keymap.set("i", "jk", "<Esc>", { desc = "Exit insert mode" })
vim.keymap.set({ "n", "v" }, "mm", "%", { desc = "Jump between parens" })
vim.keymap.set("n", "Y", "yy", { desc = "Yank whole line" })
vim.keymap.set({ "n", "v" }, "ss", "<cmd>:w<cr>", { desc = "Save" })
vim.keymap.set("n", "<C-x><C-s>", "<cmd>:w<cr>", { desc = "Save" })
vim.keymap.set("n", "<leader>q", "<cmd>:bd<cr>", { desc = "Close buffer" })
vim.keymap.set("v", "<", "<gv", { desc = "Indent left <" })
vim.keymap.set("v", ">", ">gv", { desc = "Indent left >" })
